### ISSUE TITLE
"Staking via the Website" within the guide shows a wrong interface (and more)

### ISSUE THREAD

**Issue by OrganicParty** [rocket-pool/docs.rocketpool.net#16]
Hi guys,
Not sure if that's the right place to post this (I'm totally new to GitHub).

Pay attention that the UI show here
https://docs.rocketpool.net/guides/node/create-validator.html#staking-via-the-website
is different that how it really looks (which for me looks quite odd with no feedback as to which node you're staking, like it shown in the guidebook).

Also, maybe that was a coincidence but for me the "via the website" didn't work. I did everything by the guidebook, the transaction succeed in Etherscan but failed in the website. Take a look: https://etherscan.io/tx/0xb859a66d67f06b9b4c8b4b16c659b59b0a9ab419445ea6ee11381db428da24f2

![image](https://github.com/rocket-pool/docs.rocketpool.net/assets/137222512/87c111df-05a9-4ab9-9015-ecaed8d3be07)

Thanks!

**Comment by nickdoherty** [comment]
Thanks for opening up the issue.

I believe what occurred here is your Approve transaction returned an error to the UI for whatever reason, but was a successful transaction. This meant that the state events that check for approved tokens wouldn't have fired and meant you didn't progress to the next screen.

The docs site reflect the UI & UX as they currently appear on the staking sites so I will be closing this issue. It seems you got stuck on the approval screen and didn't progress to the stake on behalf of node screen. 

Totally acknowledge that the UX/UI would have been confusing after this step, however it appears you hit some sort of anomoly when receiving a message back from the RPC. 

I successfully tested this a few times (approve then stake on behalf) using Metamask.
