### ISSUE TITLE
Small change description minipool balance

### ISSUE THREAD

**Issue by Elevator8-source** [rocket-pool/docs.rocketpool.net#30]
The current description to the minipool balance in Grafana is this: "This is how much ETH is currently available for distribution **in each** of your minipool contracts (on the execution layer). Note that if any of them have a refund, this shows the total balance minus that refund amount - in other words, it shows whatever's left over after your refund."

![image](https://github.com/rocket-pool/docs.rocketpool.net/assets/105308065/b706fb34-cc65-479b-8f11-9421be744fc1)

I do not think this number is the amount that is available in each, shouldn't it be "in all"?

**Comment by Thirawat11** [comment]
S

**Comment by nickdoherty** [comment]
Hey @SgtDinosaur, thanks for letting us know. I have applied the fix in the relevant repository.
