### ISSUE TITLE
Explain validator queue better

### ISSUE THREAD

**Issue by Valdorff** [rocket-pool/docs.rocketpool.net#50]
In create-validator.md
> Once the Beacon Chain accepts both of the deposits (one from you and one from the staking pool), your validator will enter the Beacon Chain queue where it will wait for its turn to become activated and start staking.

Maybe mention that it has fluctuated significantly from very fast to over a month and link to https://www.validatorqueue.com/?

**Comment by nickdoherty** [comment]
Hey @Valdorff, added a note to the top of the page for users to check the queue and linking to that site.
