### ISSUE TITLE
Change description for extra clearity for idiots like me ;)

### ISSUE THREAD

**Issue by Elevator8-source** [rocket-pool/docs.rocketpool.net#6]
https://docs.rocketpool.net/guides/node/create-validator.html#depositing-eth-and-creating-a-minipool

![image](https://github.com/rocket-pool/docs.rocketpool.net/assets/105308065/57813fee-0d5d-4f0f-96f8-d29ffacec0e4)

Change to something like: 

Please choose the amount of ETH bond you want to initiate and deposit:
1: 8 ETH
2: 16 ETH

I just migrated with 2 minipools and wanted to deposit 16 eth but in 2 minipools of 8 ETH individually.
With the current description it looks like you haven't made the bond size choice yet, just how much you want to deposit.
Minor language change that might bring more clarity.

**Comment by nickdoherty** [comment]
This is actually a change to the Smart Node (the docs display what the Smart Node does). Please replicate your request via the following link:

https://github.com/rocket-pool/smartnode/issues/new
