### ISSUE TITLE
Add command to figure out achitecture

### ISSUE THREAD

**Issue by miguel-neto-deel** [rocket-pool/docs.rocketpool.net#61]
https://github.com/rocket-pool/docs.rocketpool.net/blob/133ab886ab09ff241a6db2474f107b1e3df76cef/docs/guides/node/updates.md?plain=1#L126

**Comment by nickdoherty** [comment]
I've added this in. Thank you.

https://docs.rocketpool.net/guides/node/updates#updating-the-smartnode-stack
