### ISSUE TITLE
Broken images on node/prepare-node

### ISSUE THREAD

**Issue by AOrobator** [rocket-pool/docs.rocketpool.net#7]
multiple broken images and formatting are on this page. i've highlighted only 2 examples but there are many more.

<img width="1728" alt="Screenshot 2023-06-04 at 1 46 29 PM" src="https://github.com/rocket-pool/docs.rocketpool.net/assets/4106884/e4a592a2-31c1-4412-bcdb-85bebcc54d04">

**Comment by nickdoherty** [comment]
Thanks for letting me know, this has been corrected.
