### ISSUE TITLE
Remove `--smartnode-web3StorageApiToken`

### ISSUE THREAD

**Issue by yakimant** [rocket-pool/docs.rocketpool.net#74]
From [docs/guides/odao/setup.md](https://github.com/rocket-pool/docs.rocketpool.net/blob/main/docs/guides/odao/setup.md)

See https://github.com/rocket-pool/smartnode/commit/15d7c76b6ad0a4b0da5a0fd83519f7f44f2fc690

**Comment by yakimant** [comment]
Also:
https://github.com/rocket-pool/docs.rocketpool.net/blob/main/docs/guides/odao/overview.md

**Comment by nickdoherty** [comment]
Thanks for pointing this out @yakimant, this has been addressed.
