### ISSUE TITLE
Invalid command: faucet status

### ISSUE THREAD

**Issue by nikkolasg** [rocket-pool/docs.rocketpool.net#87]
Hi there,

I just downloaded yesterday rocketpool, and am trying to follow the docs to setup first a node on Holesky. I got to a point where i wanted to get some RPL tokens from the faucet, from [this page](https://docs.rocketpool.net/guides/testnet/overview#getting-test-rpl-on-holesky) using the command
```
rocketpool faucet status
```
but all i'm getting is
```
rocketpool faucet status

No help topic for 'faucet'
```
Doesn't seem like the faucet subcommand exists anymore. or if it does, is it because i installed a wrong version or stg ? I simply downloaded via docker fully managed solution. What can i do ? 

I tried to search a bit on the github but didn't find anything helpful there...

Thank you for your help.

**Comment by nickdoherty** [comment]
hey @nikkolasg, the faucet command has been retired and the best place to get test RPL is the discord. I've adjusted the docs to reflect this. 

Thank you for pointing this out.
