### ISSUE TITLE
Add ShapeShift as a wallet integration

### ISSUE THREAD

**Issue by firebomb1** [rocket-pool/docs.rocketpool.net#99]
ShapeShift's platform allows entering/exiting RocketPool pools and also support rETH as an asset for all wallet operations. It should be listed in https://docs.rocketpool.net/overview/contracts-integrations#integrations

I will make a PR to accomplish this.

Disclosure: I'm a contributor in the ShapeShift DAO, part of the Marketing Business Development workstream.

**Comment by firebomb1** [comment]
Screenshots displaying the current integration:

rETH on multiple chains:
![image](https://github.com/user-attachments/assets/dc9b3d3f-8903-4bdd-97fa-a520cfae4472)

Cross-chain route to rETH:
![image](https://github.com/user-attachments/assets/49994c72-eb7a-4ece-9824-cff042c70789)

**Comment by firebomb1** [comment]
Hello @nickdoherty, I've noticed that you've started listing integrations on the website now too (https://rocketpool.net/protocol/integrations). It seems based on the list maintained in this repo with the addition of logo? It looks really nice, thanks for listing us there too! 

We've recently updated [our brand assets](https://shapeshift.com/brand-assets)  and I wanted to know where I should submit the new logo to update the list on the website?

Here's the SVG version, I've picked the with a transparent background and a white stroke as it seems to fit the default theme, but if you need something else tell me:

![FOX_white](https://github.com/user-attachments/assets/56eb6bc6-74cd-414f-92cb-5bf554b92fab)

**Comment by nickdoherty** [comment]
hey @firebomb1 apologies for the delay, the team have been away at Devcon. 

I've updated the logo for you. Let me know if there are any issues.

**Comment by firebomb1** [comment]
Hey @nickdoherty ! Awesome, it looks great. Thanks for the quick change, hope Devcon was fun!
